
### Login auth: public

Get http://localhost:3300/login



### POST User Routes auth: public

Post http://localhost:3300/users
Content-Type: application/json

{
    "firstName": "Jarryd",
    "lastName": "Johnson",
    "role": "admin"
}

### Dashboard auth: users

Get http://localhost:3300/dashboard
Content-Type: application/json

{
    "userId": 1
}



### Get Vehicles auth: ADMIN

get http://localhost:3300/vehicles
Content-Type: application/json

{
    "userId": 2
}

### Show Vehicle auth: ADMIN or VEHICLE_DRIVER

get http://localhost:3300/vehicles/2
Content-Type: application/json

{
    "userId": 2
}

### GET Drivers auth: admin

Get http://localhost:3300/users
Content-Type: application/json

{
    "_id": "62ccad750c6b8ee48710ff44"

}

### DELETE user auth: admin

Delete http://localhost:3300/users/62ce39abc43c697ecc3f3756
Content-Type: application/json

{
    "_id": "62ce37af998dbb9188235627"

}


### UPDATE user auth: admin

Put http://localhost:3300/users/62ce3198fa3884cf0f177581
Content-Type: application/json

{
    "_id": "62ce31a5fa3884cf0f177583",
    "firstName": "Mike",
    "lastName": "Salisbury",
    "vehicle": "62ce3bc185c51ff0c5923cca"

}