
### POST / RUNS / ADMIN
Post http://localhost:3300/api/v1/runs
Content-Type: application/json

{
    "_id": "62ccad750c6b8ee48710ff44",
    "name": "Route 4",
    "area": "Ballina"
}


### GET  / RUNS / ADMIN

Get http://localhost:3300/api/v1/runs
Content-Type: application/json

{
    "_id": "62ccad750c6b8ee48710ff44"

}


### GET / A RUN / ADMIN

Get http://localhost:3300/api/v1/runs/62cd1373b40d9c6f4ddccf2e
Content-Type: application/json

{
    "_id": "62ccad750c6b8ee48710ff44"

}


### DELETE / A RUN / ADMIN
Delete http://localhost:3300/api/v1/runs/62cd1373b40d9c6f4ddccf2e
Content-Type: application/json

{
    "_id": "62ccad750c6b8ee48710ff44"

}

### UPDATE / A RUN / ADMIN or RUN
Put http://localhost:3300/api/v1/runs/62cd1373b40d9c6f4ddccf2e
Content-Type: application/json

{
    "_id": "62ccad750c6b8ee48710ff44",
    "name": "Route 4",
    "area": "Sunshine Coast"

}


