
### Login auth: public

Get http://localhost:23087/api/v1/login



### POST User Routes auth: public

Post http://localhost:3405/api/v1/users/register
Content-Type: application/json

{
    "email": "Sam@wizzcouriers.com",
    "firstName": "Sam",
    "lastName": "Davis",
    "password": "123456",
    "passwordCheck": "123456",
    "role": "driver"
}

### POST User Routes auth: public

Post http://localhost:3405/api/v1/users/login
Content-Type: application/json

{
    "email": "greg@wizzcouriers.com",
    "firstName": "Greg",
    "lastName": "Johnson",
    "password": "123456",
    "passwordCheck": "123456",
    "role": "admin"
}





### GET Drivers auth: admin

Get http://localhost:3405/api/v1/users
Content-Type: application/json

# {
#     "_id": "62d3e058daf07ad643bf7629"
# }

### DELETE user auth: admin

Delete http://localhost:3405/api/v1/users/62ce39abc43c697ecc3f3756
Content-Type: application/json

{
    "_id": "62d3e058daf07ad643bf7629"

}


### UPDATE user auth: admin

Put http://localhost:3405/api/v1/users/62ce3198fa3884cf0f177581
Content-Type: application/json

{
    "_id": "62d3e058daf07ad643bf7629",
    "firstName": "Mike",
    "lastName": "Salisbury",
    "vehicle": "62ce3bc185c51ff0c5923cca"

}

### GET driver by email

Get http://localhost:3405/api/v1/drivers





### GET driver by email

Get http://localhost:3405/api/v1/drivers/find
Content-Type: application/json

{
    "email": "bob@wizzcouriers.com"

}

### Assign vehicle to driver

Put http://localhost:3405/api/v1/drivers/62ce8fd7b342975e04bb01cc
Content-Type: application/json

{
    "vehicleRegistration": "BCD212"

}