### GET - Admin

Get http://localhost:3405/api/v1/vehicles
Content-Type: application/json



### POST- Admin

Post http://localhost:3405/api/v1/vehicles
Content-Type: application/json
{
    "_id": "62d7f9b7340c2886c0abb226",
    "make": "Mercedes",
    "model": "Sprinter",
    "year": "2022",
    "registration": "BRN201",
    "user": "62d7fa0c340c2886c0abb22b",
    "kilometers": "5022",
    "nextService": "10000"
}


### GET a vehicle - admin or vehicle driver

Get http://localhost:3405/api/v1/vehicles/62cd672dc738ad24f929f0b0

{
    "_id": "62ccd3eecada19e652d3a0a4"

}

### PUT - admin or vehicle driver

Put http://localhost:3405/api/v1/vehicles/62cd672dc738ad24f929f0b0
Content-Type: application/json

{
    "_id": "62cd62d2686cd30e922d2a80",
    "kilometers": "212000",
    "condition": "Broken CV joint"

}

### DELETE - admin

Delete http://localhost:3405/api/v1/vehicles/62cd672dc738ad24f929f0b0
Content-Type: application/json

{
    "_id": "62ce31a5fa3884cf0f177583"
}