### GET - Admin

Get http://localhost:3405/api/v1/vehicles
Content-Type: application/json

### GET A Vehicle by Registration - Admin

Get http://localhost:3405/api/v1/vehicles/DSC222
Content-Type: application/json

### PUT Vehicle by Registration - Admin

Put http://localhost:3405/api/v1/vehicles/DSC222
Content-Type: application/json

{
  "_id": "62d8af87ddd83f8478a61586",
  "make": "Volvo",
  "model": "FH18",
  "year": "2020",
  "registration": "DSC222",
  "kilometers": "58022",
  "nextService": "65000",
  "condition": "Satisfactory",
  "__v": 0
}


### POST- Admin

Post http://localhost:3405/api/v1/vehicles
Content-Type: application/json
{
    "_id": "62d7f9b7340c2886c0abb226",


### GET a vehicle - admin or vehicle driver

Get http://localhost:3405/api/v1/vehicles/62cd672dc738ad24f929f0b0

{
    "_id": "62ccd3eecada19e652d3a0a4"

}

### PUT - admin or vehicle driver

Put http://localhost:3405/api/v1/vehicles/62cd672dc738ad24f929f0b0
Content-Type: application/json

{
    "_id": "62cd62d2686cd30e922d2a80",
    "kilometers": "212000",
    "condition": "Broken CV joint"

}

### DELETE - admin

Delete http://localhost:3405/api/v1/vehicles/62cd672dc738ad24f929f0b0
Content-Type: application/json

{
    "_id": "62ce31a5fa3884cf0f177583"
}